name: traefik-odroid

services:
  traefik:
    image: traefik:v3.6
    container_name: traefik-odroid
    hostname: traefik-odroid
    restart: unless-stopped
    networks:
      proxy:
      shared_macvlan:
        ipv4_address: 192.168.144.15
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.config.yaml:/etc/traefik/traefik.yaml:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  proxy:
    external: true
  shared_macvlan:
    external: true
