name: home-traefik

services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    networks:
      proxy:
      shared_macvlan:
        ipv4_address: 192.168.144.15
    ports:
      - "80:80"
      - "443:443"
      - 8080:8080
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/:/etc/traefik/:ro
      - ./certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=qZ4KC0hDadb4Uqny5QWCndVrD6a02cr264YAb6q

networks:
  proxy:
    external: true
  shared_macvlan:
    external: true
