---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# --> (Optional) Change log level and format here ...
#     - level: [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
log:
  level: [INFO, WARN, ERROR, FATAL]
# <--

accessLog:
  format: json
  filters:
    statusCodes:
      - "200"
      - "400-404"
      - "500-503"
  fields:
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Content-Type: keep

# --> (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
  insecure: true
# <--

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    # --> (Optional) Redirect all HTTP to HTTPS
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    # <--
  websecure:
    address: :443

# -- Configure your CertificateResolver here...
certificatesResolvers:
  cloudflare:
    acme:
      email: joezergullo@gmail.com # <-- Change this to your email
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare # <-- (Optional) Change this to your DNS provider
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# --> (Optional) Disable TLS Cert verification check
# serversTransport:
#   insecureSkipVerify: true
# <--

providers:
  docker:
    exposedByDefault: false # <-- (Optional) Change this to true if you want to expose all services
    # Specify discovery network - This ensures correct name resolving and possible issues with containers, that are in multiple networks.
    # E.g. Database container in a separate network and a container in the frontend and database network.
    network: proxy
  file:
    directory: /etc/traefik
    watch: true

# --> (Example) Expose an external service using Traefik...
http:
  # -- Change Router Configuration here...
  routers:
    grafana:
      rule: "Host(`grafana.optiplex.home`)" # <-- Change Rules here...
      service: grafana-svc # <-- Change Service Name here...
      priority: 1000 # <-- (Optional) Change Routing Priority here...
      entryPoints:
        - web
        # - websecure
      # tls:
      #   certResolver: cloudflare

  # -- Change Service Configuration here...
  services:
    grafana-svc: # <-- Change Service Name here...
      loadBalancer:
        servers:
          - url: "http://192.168.144.45:3000" # <-- Change Target Service URL here...
# <--
